# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fix nlmixr2 save output
#'
#' This function modifies the output of nlmixr2's save function to ensure that
#' the "Estimate" and "SE" fields are numeric vectors with appropriate names,
#' rather than data frames. This is necessary for compatibility with other
#' functions that expect these fields to be numeric vectors.
#'
#' @param obj A list object returned by nlmixr2's save function.
#'
#' @return A modified data.frame object with "Estimate" and "SE" as named numeric vectors
#'
#' @keywords internal
#'
#' @export
#'
nlmixr2saveParFixedDf <- function(obj) {
    .Call(`_nlmixr2save_nlmixr2saveParFixedDf`, obj)
}

